[build-system]
requires = ["uv_build>=0.10.0,<0.12"]
build-backend = "uv_build"

[project]
name = "dev-sync"
version = "0.0.0"
description = ""
readme = "README.md"
authors = [
  {name = "Markus Hofbauer"}
]
requires-python = ">=3.10"
dependencies = [
  "PyYAML",
  "gitpython",
  "coloredlogs",
  "verboselogs"
]

[project.scripts]
devsync = "devsync:main"

[project.optional-dependencies]
dev = [
  "pytest>=9.0.3",
  "pytest-cov",
  "pyfakefs",
  "pytest-subprocess",
  "pytest-sugar"
]

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]

[tool.flake8.known-modules]
"" = ["dev_sync"]

[tool.pylint.BASIC]
# Stick to snake case, but accept setUp and tearDown from unittest
method-rgx = "(([a-z_][a-z0-9_]*)|(setUp)|(tearDown))$"

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.MASTER]
# Add files or directories to the blacklist. They should be base names, not paths.
ignore = ["venv"]

[tool.pylint."MESSAGES CONTROL"]
# Only show warnings with the listed confidence levels. Leave empty to show
# all. Valid levels: HIGH, INFERENCE, INFERENCE_FAILURE, UNDEFINED
confidence = ""
disable = [
  "missing-function-docstring",
  "missing-class-docstring",
  "missing-module-docstring",
  "import-error", # disabled since pre-commit runs pylint in a separate venv
  "unspecified-encoding",
  "fixme",
  "too-few-public-methods",
  "no-name-in-module"
]

[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov=dev_sync -vv"
testpaths = [
  "tests"
]

[tool.ruff]
fix = true
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",
  "ARG",
  "COM", # Done by the formatter
  "D100", # In our opinion overkill
  "D101", # In our opinion overkill
  "D102", # In our opinion overkill
  "D103",
  "D104", # In our opinion overkill
  "D105", # In our opinion overkill
  "D106", # In our opinion overkill
  "D107", # In our opinion overkill
  "D203", # Conflicts with ruff-format, incpompatible with D211
  "D213", # Incompatible with D212
  "ISC001", # Conflicts with formatter
  "FBT",
  "FIX",
  "PT", # TODO convert to pytest
  "S", # TODO resolve after pytest conversion
  "T",
  "TD"
]

[tool.uv.build-backend]
module-root = "" # required to avoid the "src" layout, which is the default for uv_build
